config/routes.rb
Rails.application.routes.draw do
  devise_for :users,
    path: '',
    path_names: {
      sign_in: 'login',
      sign_out: 'logout',
      password: 'password',
      confirmation: 'verification',
      registration: 'register',
      sign_up: 'signup'
    }
  resources :users, only: [:index, :show] do
    resources :posts, only: [:index, :show, :new, :create, :destroy] do
      resources :comments, only: [:new, :create, :destroy]
      resources :likes, only: [:create]
    end
  end
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root 'users#index'
end

app/models/comment.rb
# frozen_string_literal: true

# Comments model
class Comment < ApplicationRecord
  belongs_to :post
  belongs_to :author, class_name: 'User'

  after_save :update_comments_counter

  after_destroy :update_comments_counter

  def update_comments_counter
    post.update(comments_counter: post.comments.length)
  end
end

app/controllers/comments_controller.rb
# frozen_string_literal: true

# handels comment creation
class CommentsController < ApplicationController
  def new
    @current_user = current_user
    @post_id = params[:post_id]
    @comment = Comment.new
  end

  def create
    @current_user = current_user
    @post_id = params[:post_id]
    comment = Comment.new(comment_params.merge(author: @current_user, post_id: @post_id))
    if comment.save
      redirect_to user_post_path(@current_user.id, @post_id), cyan: 'your view is noted!'
    else
      flash.now[:red] = 'comment not posted!'
      render :new
    end
  end

  def destroy
    @post = Post.find(params[:post_id])
    @comment = Comment.find(params[:id])
    @comment.destroy
    flash[:cyan] = 'comment deleted.'
    redirect_to user_post_path(params[:post_id])
  end

  private

  def comment_params
    params.require(:comment).permit(:text)
  end
end

app/helpers/comments_helper.rb
# frozen_string_literal: true

# comments helper
module CommentsHelper
end

app/views/comments/_new.html.erb
<div class="mx-4 mb-6">
  <%= form_with model: @comment, url: user_post_comments_path(@current_user.id, @post.id), class: "w-full min-w-full" do |form| %>
    <div class="flex items-center border-b border-gradient-to-r from-cyan-500 to-blue-500 p-0">
      <%= form.text_field :text, required: true, class: "appearance-none bg-transparent border-none w-3/4 text-gray-700 mr-3 pt-1 px-2 leading-tight focus:outline-none", placeholder: "what's your opinion?" %>
      <%= form.submit "Comment", class: "lex-shrink-0 rounded-lg bg-gradient-to-r from-cyan-500 to-blue-500 p-1 px-4 mt-4 mb-3 text-slate-50" %>
    </div>
  <% end %>
</div>