config/routes.rb
Rails.application.routes.draw do
  devise_for :users,
    path: '',
    path_names: {
      sign_in: 'login',
      sign_out: 'logout',
      password: 'password',
      confirmation: 'verification',
      registration: 'register',
      sign_up: 'signup'
    }
  resources :users, only: [:index, :show] do
    resources :posts, only: [:index, :show, :new, :create, :destroy] do
      resources :comments, only: [:new, :create, :destroy]
      resources :likes, only: [:create]
    end
  end
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root 'users#index'
end

app/models/user.rb
# frozen_string_literal: true

# User model
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :comments, foreign_key: :author_id, dependent: :destroy
  has_many :likes, foreign_key: :author_id, dependent: :destroy
  has_many :posts, foreign_key: :author_id, dependent: :destroy
  validates :name, presence: true
  validates :posts_counter, numericality: { only_integer: true, greater_than_or_equal_to: 0 }

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable,
         :confirmable

  ROLES = %i[admin user].freeze

  def is?(requested_role)
    role == requested_role.to_s
  end

  def recent_posts
    posts.order(created_at: :desc).limit(3)
  end
end

app/controllers/users/devise_controller.rb
# frozen_string_literal: true

module Users
  # modified devise controller
  class DeviseController < ApplicationController
    # responder for pushing flash messages
    class Responder < ActionController::Responder
      def to_turbo_stream
        controller.render(options.merge(formats: :html))
      rescue ActionView::MissingTemplate => e
        # rubocop:disable Style/GuardClause
        if get?
          raise e
        elsif has_errors? && default_action
          render rendering_options.merge(formats: :html, status: :unprocessable_entity)
        else
          redirect_to navigation_location
        end
        # rubocop:enable Style/GuardClause
      end
    end

    self.responder = Responder
    respond_to :html, :turbo_stream
  end
end

app/controllers/users_controller.rb
# frozen_string_literal: true

# List and display user
class UsersController < ApplicationController
  before_action :authenticate_user!

  def index
    @users = User.all
    @current_user = current_user
    @post = Post.new
  end

  def show
    @current_user = current_user
    @user = User.find(params[:id])
    @posts = @user.recent_posts.includes(:comments)
  end
end

app/helpers/users_helper.rb
# frozen_string_literal: true

# User Helper
module UsersHelper
end

app/views/users/_post.html.erb
<%= link_to user_post_path(@user.id, post.id), class: "flex flex-col  rounded-lg border justify-between pt-2 pl-3 pr-3 leading-normal min-w-full m-2 hover:bg-gray-100" do %>
  <h2 class="mb-3 font-bold text-gray-700">#<%= post.id %> <%= post.title %> </h2>
  <p class="mb-3 font-normal text-gray-700"><%= post.text[0..120]%><%= post.text.length > 121? "..." : ''%></p>
  <p class="mb-3 font-normal text-gray-700mb-3 font-normal text-gray-500 text-xs text-right">
    <span class="flex text-right font-normal text-gray-500 self-end">
      <span class="flex items-center">
        <svg xmlns="http://www.w3.org/2000/svg" class="h-4 w-4" fill="none" viewBox="0 0 24 24" stroke="currentColor" stroke-width="2">
          <path stroke-linecap="round" stroke-linejoin="round" d="M8 10h.01M12 10h.01M16 10h.01M9 16H5a2 2 0 01-2-2V6a2 2 0 012-2h14a2 2 0 012 2v8a2 2 0 01-2 2h-5l-5 5v-5z" />
        </svg>
        &nbsp;
        <%= post.comments_counter %>
      </span>
      &nbsp; 	&nbsp;
      <span class="flex items-center">
        <svg xmlns="http://www.w3.org/2000/svg" class="h-4 w-4" fill="none" viewBox="0 0 24 24" stroke="currentColor" stroke-width="2">
          <path stroke-linecap="round" stroke-linejoin="round" d="M4.318 6.318a4.5 4.5 0 000 6.364L12 20.364l7.682-7.682a4.5 4.5 0 00-6.364-6.364L12 7.636l-1.318-1.318a4.5 4.5 0 00-6.364 0z" />
        </svg>
        &nbsp;
        <%= post.likes_counter %>
      </span>
    </span>
  </p>
<%end%>

app/views/users/_user.html.erb
<%= link_to user_path(user.id), class: "flex flex-col items-center bg-white rounded-lg border shadow-md md:flex-row md:max-w-xl hover:bg-gray-100 m-auto mt-4 md-4" do %>
  <img class="object-cover w-full h-96 aspect-square rounded-t-lg md:h-auto md:w-48 md:rounded-none md:rounded-l-lg" src="<%= user.photo || "https://upload.wikimedia.org/wikipedia/commons/7/7c/Profile_avatar_placeholder_large.png" %>" alt="<%= user.name %>">
  <div class="flex flex-col justify-between p-4 leading-normal">
    <h3 class="mb-2 text-2xl font-bold tracking-tight text-gray-900"><%= user.name %></h3>
    <p class="mb-3 font-normal text-gray-700"> posts: <%= user.posts_counter %></p>
  </div>
<% end %>

app/views/users/index.html.erb
<div class="m-auto 2xl:w-2/4 lg:3/4 md:w-5/6 md:max-w-xl">
  <% if user_signed_in? %>
    <div class="flex flex-col items-center bg-white rounded-lg border shadow-md md:flex-row md:max-w-xl m-auto my-6">
      <div class="flex flex-col justify-between p-4 leading-normal min-w-full">
        <h2 class="text-2xl font-bold m-auto leading-loose text-left text-grey-700">
          Hello <%= @current_user.name %>!
        </h2>
        <%= render "posts/new", :post => @post %>
      </div>
    </div>
  <% end %>
  <h1 class="text-4xl font-bold m-auto leading-loose pl-1 pt-6 pd-6 text-left text-grey-700">
    all users.
  </h1>
  <div class="container mb-12">
    <%= render partial: "user", collection: @users.order(:id) %>
  </div>
</div>

app/views/users/show.html.erb
<div class="m-auto 2xl:w-2/4 lg:3/4 md:w-5/6 md:max-w-xl">
  <div class="flex flex-col items-center bg-white rounded-lg border shadow-md md:flex-row md:max-w-xl m-auto mt-4 md-4">
    <img class="object-cover w-full h-96 aspect-square rounded-t-lg md:h-auto md:w-48 md:rounded-none md:rounded-l-lg" src="<%= @user.photo || "https://upload.wikimedia.org/wikipedia/commons/7/7c/Profile_avatar_placeholder_large.png" %>" alt="<%= @user.name %>">
    <div class="flex flex-col justify-between p-4 leading-normal">
      <h1 class="mb-2 text-3xl font-bold tracking-tight text-gray-900"><%= @user.name %></h1>
      <p class="mb-3 font-normal text-gray-700"> posts: <%= @user.posts_counter %></p>
    </div>
  </div>
  <div class="flex flex-col items-center bg-white rounded-lg border shadow-md md:flex-row md:max-w-xl m-auto mt-4 md-4">
    <div class="flex flex-col justify-between p-4 leading-normal">
      <h2 class="mb-3 font-bold text-gray-700">bio.</h2>
      <p class="mb-3 font-normal text-gray-700"><%= @user.bio %></p>
    </div>
  </div>
  <div class="flex flex-col items-center bg-white rounded-lg border shadow-md  md:max-w-xl m-auto mt-4 md-4 p-4">
    <div class="flex flex-col justify-between leading-normal min-w-full md-4">
      <h2 class="mb-3 font-bold text-gray-700">recent posts.</h2>
    </div>
    <% if @posts.length > 0 %>
      <%= render partial: "post", collection: @posts %>
      <%= link_to "see all posts.", user_posts_path(@user.id), class: "rounded-lg bg-gradient-to-r from-cyan-500 to-blue-500 p-2 pr-4 pl-4 mt-6 text-slate-50" %>
    <% else %>
      <p class="font-normal text-gray-700">zero posts from this user.</p>
    <% end %>
  </div>
</div>