config/routes.rb
Rails.application.routes.draw do
  devise_for :users,
    path: '',
    path_names: {
      sign_in: 'login',
      sign_out: 'logout',
      password: 'password',
      confirmation: 'verification',
      registration: 'register',
      sign_up: 'signup'
    }
  resources :users, only: [:index, :show] do
    resources :posts, only: [:index, :show, :new, :create, :destroy] do
      resources :comments, only: [:new, :create, :destroy]
      resources :likes, only: [:create]
    end
  end
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root 'users#index'
end

app/models/post.rb
# frozen_string_literal: true

# Post model
class Post < ApplicationRecord
  belongs_to :author, class_name: 'User'
  has_many :comments, dependent: :destroy
  has_many :likes, dependent: :destroy
  validates :title, presence: true, length: { maximum: 250 }
  validates :comments_counter, numericality: { only_integer: true, greater_than_or_equal_to: 0 }
  validates :likes_counter, numericality: { only_integer: true, greater_than_or_equal_to: 0 }

  after_save :update_posts_counter

  after_destroy :update_posts_counter

  def recent_comments
    comments.order(created_at: :desc).limit(5)
  end

  private

  def update_posts_counter
    author.update(posts_counter: author.posts.length)
  end
end

app/controllers/posts_controller.rb
# frozen_string_literal: true

# List and display posts from a user
class PostsController < ApplicationController
  def index
    @user = User.find(params[:user_id])
    @posts = @user.posts.includes(:comments)
    @current_user = current_user
  end

  def show
    @user = User.find(params[:user_id])
    @post = Post.find(params[:id])
    @current_user = current_user
    @comment = Comment.new
  end

  def new
    @current_user = current_user
    @post = Post.new
    @user = current_user
  end

  def create
    @current_user = current_user
    @post = @current_user.posts.new(post_params)
    if @post.save
      redirect_to user_path(@current_user.id), cyan: 'thought posted.'
    else
      flash.now[:red] = @post.errors.full_messages.join(', ')
      render :new
    end
  end

  def destroy
    @post = Post.find(params[:id])
    @post.destroy
    flash.now[:success] = 'post deleted.'
    redirect_to user_path(params[:user_id])
  end

  def post_params
    params.require(:post).permit(:title, :text, :user_id)
  end
end

app/helpers/posts_helper.rb
# frozen_string_literal: true

# Post Helper
module PostsHelper
end

app/views/posts/_comment.html.erb
<div class="flex flex-col rounded-lg border justify-between pt-2 pl-2 pr-2 leading-normal min-w-full mt-1 md-1">
  <p class="mb-3 font-normal text-sm text-gray-700">
    <span><%= comment.author.name %>: </span>
    <span><%= comment.text %> </span>
    <% if can? :destroy, comment%>
      <%= button_to "Delete", user_post_comment_path(comment.author_id, comment.post_id, comment.id), method: :delete, class: "bg-transparent hover:bg-red-500 text-red-700 font-semibold hover:text-white px-4 border border-red-500 hover:border-transparent rounded text-xs" %>
    <% end %>
  </p>
</div>

app/views/posts/_empty.html.erb
<p class="mb-3 font-normal text-gray-700">zero comments for this post.</p>

app/views/posts/_likes_and_comments.html.erb
<span class="flex text-right font-normal text-xs self-end">
  <span class="flex rounded-lg bg-gradient-to-r from-cyan-500 to-blue-500 p-2 pr-4 pl-4 text-white">
    <span class="flex items-center">
      <svg xmlns="http://www.w3.org/2000/svg" class="h-4 w-4" fill="none" viewBox="0 0 24 24" stroke="currentColor" stroke-width="2">
        <path stroke-linecap="round" stroke-linejoin="round" d="M8 10h.01M12 10h.01M16 10h.01M9 16H5a2 2 0 01-2-2V6a2 2 0 012-2h14a2 2 0 012 2v8a2 2 0 01-2 2h-5l-5 5v-5z" />
      </svg>
      &nbsp;
      <%= @post.comments_counter %>
    </span>
  </span>
  &nbsp; 	&nbsp;
  <%= button_to user_post_likes_path(@current_user.id, @post.id), method: :post, class: "flex rounded-lg bg-gradient-to-r from-cyan-500 to-blue-500 p-2 pr-4 pl-4 text-white" do %>
    <span class="flex items-center">
      <svg xmlns="http://www.w3.org/2000/svg" class="h-4 w-4" fill="none" viewBox="0 0 24 24" stroke="currentColor" stroke-width="2">
        <path stroke-linecap="round" stroke-linejoin="round" d="M4.318 6.318a4.5 4.5 0 000 6.364L12 20.364l7.682-7.682a4.5 4.5 0 00-6.364-6.364L12 7.636l-1.318-1.318a4.5 4.5 0 00-6.364 0z" />
      </svg>
      &nbsp;
      <%= @post.likes_counter %>
    </span>
  <% end %>
</span>

app/views/posts/_new.html.erb
<%= form_with model: @post, class: "bg-white rounded px-4 pt-6 py-1 mb-4 min-w-full", url: user_posts_path(@current_user.id), local: true do |form| %>
  <div class="mb-4">
    <%= form.text_field :title, class: "shadow appearance-none border rounded w-full py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline", placeholder: "what's on your mind?"%>
  </div>
  <div class="mb-3">
    <%= form.text_area :text, class: "shadow appearance-none border rounded w-full py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline", placeholder: "now describe that thought." %>
  </div>
  <%= form.submit "post", class: "rounded-lg bg-gradient-to-r from-cyan-500 to-blue-500 p-2 pr-6 pl-6 text-slate-50" %>
<% end %>

app/views/posts/_post.html.erb
<%= link_to user_post_path(@user.id, post.id), class: "flex flex-col  rounded-lg border justify-between p-3 leading-normal min-w-full m-2 hover:bg-gray-100" do %>
  <h2 class="mb-3 font-bold text-gray-700">#<%= post.id %> <%= post.title %></h2>
  <p class="mb-3 font-normal text-gray-700"><%= post.text[0..120]%><%= post.text.length > 121? "..." : ''%></p>
  <p class="mb-3 font-normal text-gray-500 text-xs text-right">
    <div class="flex flex-row text-right font-normal text-gray-500 self-end">
      <span class="flex items-center">
        <svg xmlns="http://www.w3.org/2000/svg" class="h-4 w-4" fill="none" viewBox="0 0 24 24" stroke="currentColor" stroke-width="2">
          <path stroke-linecap="round" stroke-linejoin="round" d="M8 10h.01M12 10h.01M16 10h.01M9 16H5a2 2 0 01-2-2V6a2 2 0 012-2h14a2 2 0 012 2v8a2 2 0 01-2 2h-5l-5 5v-5z" />
        </svg>
        &nbsp;
        <%= post.comments_counter %>
      </span>
      &nbsp; 	&nbsp;
      <span class="flex items-center">
        <svg xmlns="http://www.w3.org/2000/svg" class="h-4 w-4" fill="none" viewBox="0 0 24 24" stroke="currentColor" stroke-width="2">
          <path stroke-linecap="round" stroke-linejoin="round" d="M4.318 6.318a4.5 4.5 0 000 6.364L12 20.364l7.682-7.682a4.5 4.5 0 00-6.364-6.364L12 7.636l-1.318-1.318a4.5 4.5 0 00-6.364 0z" />
        </svg>
        &nbsp;
        <%= post.likes_counter %>
      </span>
    </div>
  </p>
  <h2 class="mb-3 font-bold text-gray-700"> <%= post.comments.length > 0 ? 'comments.': ''%></h2>
  <%= render partial: "comment", collection: post.recent_comments %>
<%end%>

app/views/posts/index.html.erb
<div class="m-auto 2xl:w-2/4 lg:3/4 md:w-5/6 md:max-w-xl">
  <div class="flex flex-col items-center bg-white rounded-lg border shadow-md md:flex-row md:max-w-xl m-auto mt-4 md-4">
    <img class="object-cover w-full h-96 aspect-square rounded-t-lg md:h-auto md:w-48 md:rounded-none md:rounded-l-lg" src="<%= @user.photo || "https://upload.wikimedia.org/wikipedia/commons/7/7c/Profile_avatar_placeholder_large.png" %>" alt="<%= @user.name %>">
    <div class="flex flex-col justify-between p-4 leading-normal">
      <h1 class="mb-2 text-3xl font-bold tracking-tight text-gray-700"><%= @user.name %></h1>
      <p class="mb-3 font-normal text-gray-700"> posts: <%= @user.posts_counter %></p>
    </div>
  </div>
  <div class="flex flex-col items-center bg-white rounded-lg border shadow-md  md:max-w-xl m-auto mt-4 md-4 p-4">
    <div class="flex flex-col justify-between leading-normal min-w-full md-4">
      <h2 class="mb-3 font-bold text-gray-700">user's posts.</h2>
    </div>
    <%= render partial: "post", collection: @posts %>
  </div>
</div>

app/views/posts/new.html.erb
<div class="m-auto 2xl:w-2/4 lg:3/4 md:w-5/6 md:max-w-xl">
  <h1 class="mb-2 text-3xl font-bold tracking-tight text-gray-900 m-auto text-center pt-8">create new post.</h1>
  <div class="flex flex-col items-center bg-white rounded-lg border shadow-md md:flex-row md:max-w-xl m-auto my-6">
    <div class="flex flex-col justify-between p-4 leading-normal min-w-full">
      <%= render "posts/new", :post => @post %>
    </div>
  </div>
</div>

app/views/posts/show.html.erb
<div class="m-auto 2xl:w-2/4 lg:3/4 md:w-5/6 md:max-w-xl">
  <div class="flex flex-col  rounded-lg border justify-between p-3 leading-normal min-w-full my-2 bg-white">
    <div class="flex flex-row  rounded-lg border justify-between uppercase text-sm leading-normal min-w-full p-2 mb-4">
      <span class="font-bold text-gray-700">post#<%= @post.id %> by <%= @user.name %>.</span>
      <span class="flex items-center mx-6">
        <% if can? :destroy, @post %>
          <%= button_to "Delete", user_post_path(@post.author_id, @post.id), method: :delete, class: "bg-transparent hover:bg-red-500 text-red-700 font-semibold hover:text-white px-4 border border-red-500 hover:border-transparent rounded text-xs" %>
        <% end %>
      </span>
      <%= render partial: "likes_and_comments" %>
    </div>
    <h2 class="mb-3 font-bold text-gray-700"><%= @post.title %></h2>
    <p class="mb-3 font-normal text-gray-700"><%= @post.text%></p>
  </div>
  <h2 class="mb-3 font-bold text-gray-700"> comments.</h2>
  <div class="flex flex-col  rounded-lg border justify-between p-3 leading-normal min-w-full my-2 bg-white">
    <%= render "comments/new", :comment => @comment %>
    <% if @post.comments.length > 0 %>
      <%= render partial: "comment", collection: @post.comments %>
    <% else %>
      <p class="font-normal text-gray-700">zero comments for this post.</p>
    <% end %>
  </div>
</div>