config/routes.rb
Rails.application.routes.draw do
  devise_for :users,
    path: '',
    path_names: {
      sign_in: 'login',
      sign_out: 'logout',
      password: 'password',
      confirmation: 'verification',
      registration: 'register',
      sign_up: 'signup'
    }
  resources :users, only: [:index, :show] do
    resources :posts, only: [:index, :show, :new, :create, :destroy] do
      resources :comments, only: [:new, :create, :destroy]
      resources :likes, only: [:create]
    end
  end
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root 'users#index'
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Blog App</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>
  <body>
    <main class=" bg-slate-100 min-h-screen py-6">
      <nav class="flex items-center justify-between space-x-auto flex-wrap items-center bg-white rounded-lg border shadow-md md:flex-row md:max-w-xl m-auto px-5 py-4">
        <ul class="flex-column flex m-auto">
          <li class="flex-3 mx-2">
            <%= link_to "home.", users_path, class: "rounded-lg bg-gradient-to-r from-cyan-500 to-blue-500 p-2 pr-4 pl-4 mt-6 text-slate-50" %>
          </li>
          <% if user_signed_in? %>
            <li class="flex-3 mx-2">
              <%= link_to "my profile.", user_path(@current_user.id), class: "rounded-lg bg-gradient-to-r from-cyan-500 to-blue-500 p-2 pr-4 pl-4 mt-6 text-slate-50" %>
            </li>
            <li class="flex-3 mx-2">
              <%= link_to "my posts.", user_posts_path(@current_user.id), class: "rounded-lg bg-gradient-to-r from-cyan-500 to-blue-500 p-2 pr-4 pl-4 mt-6 text-slate-50" %>
            </li>
            <li class="flex-3 mx-2">
              <%= link_to "logout", destroy_user_session_path, method: :delete, class: "rounded-lg bg-gradient-to-r from-cyan-500 to-blue-500 p-2 pr-4 pl-4 mt-6 text-slate-50" %>
            </li>
          <% end %>
        </ul>
      </nav>
      <div class="m-auto 2xl:w-2/4 lg:3/4 p-2 md:w-5/6 md:max-w-xl font-bold flash">
        <% flash.each do |type, msg| %>
          <div class="text-<%= type %>-500">
            <%= msg %>
          </div>
        <% end %>
      </div>
      <%= yield %>
    </main>
  </body>
</html>